name: Production deployment

on:
  push:
    branches:
      - feature/migration_to_DO
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare variables
      run: |
            echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        cache-from: |
          maddevsio/madopsio:staging
        tags: maddevsio/madopsio:staging,maddevsio/madopsio:${{ env.SHORT_SHA }}

    #--------Uncomment when all packages/dependencies have been updated and vulnerabilities fixed--------#

    # - name: Run Snyk to check Docker image for vulnerabilities
    #   continue-on-error: true
    #   uses: snyk/actions/docker@master
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     image: maddevsio/maddevsio:${{ env.SHORT_SHA }}

    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@v1.1.4 # replace this with current version from https://github.com/digitalocean/app_action/releases
      with:
        app_name: madops
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        images: '[
              {
                "name": "madops",
                "image":{
                  "registry_type": "DOCKER_HUB",
                  "registry": "maddevsio",
                  "repository": "madopsio",
                  "tag": "${{ env.SHORT_SHA }}"
                }
              }
            ]'
